#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-or-later
# The installer as a command on the Live ISO. No `--config`: the operator on a
# live desktop wants the menu, and the memory environment's own launcher is the
# one that carries a prepared file.
exec python3 -m gentoo_install "$@"
