#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-or-later
# The installed command reaches bootstrap, which owns the environment checks.
case "$0" in
*/*) here=${0%/*} ;;
*)
	here=$(command -v "$0") || exit 127
	case "$here" in
	*/*) here=${here%/*} ;;
	*) here=. ;;
	esac
	;;
esac
exec "$here/../libexec/gentoo-install/bootstrap.sh" "$@"
