# SPDX-License-Identifier: GPL-2.0-or-later
"""A public key is checked before it becomes the only way into the machine."""

from __future__ import annotations

import base64
import subprocess
from dataclasses import dataclass
from pathlib import Path

import pytest

from gentoo_install.errors import ConfigError
from gentoo_install.model.paste import raw_url, url_for
from gentoo_install.model import sshkey

@dataclass(frozen=True)
class KeyCase:
    """One supported public-key wire format."""

    key_type: str
    ssh_keygen_type: str
    bits: int | None
    public_material_field: int
    security_key: bool = False


ED25519 = KeyCase("ssh-ed25519", "ed25519", None, 1)
RSA = KeyCase("ssh-rsa", "rsa", None, 2)
ECDSA_NISTP256 = KeyCase("ecdsa-sha2-nistp256", "ecdsa", 256, 2)
ECDSA_NISTP384 = KeyCase("ecdsa-sha2-nistp384", "ecdsa", 384, 2)
ECDSA_NISTP521 = KeyCase("ecdsa-sha2-nistp521", "ecdsa", 521, 2)
SK_ED25519 = KeyCase(
    "sk-ssh-ed25519@openssh.com", "ed25519", None, 1, security_key=True
)
SK_ECDSA_NISTP256 = KeyCase(
    "sk-ecdsa-sha2-nistp256@openssh.com", "ecdsa", 256, 2, security_key=True
)
KEY_CASES = (
    ED25519,
    RSA,
    ECDSA_NISTP256,
    ECDSA_NISTP384,
    ECDSA_NISTP521,
    SK_ED25519,
    SK_ECDSA_NISTP256,
)


def generated(tmp_path: Path, case: KeyCase) -> str:
    """Return one supported public-key wire format with generated material."""
    where = tmp_path / case.key_type
    command = ["ssh-keygen", "-q", "-t", case.ssh_keygen_type]
    if case.bits is not None:
        command.extend(("-b", str(case.bits)))
    command.extend(("-N", "", "-f", str(where)))
    subprocess.run(command, check=True)
    source = Path(f"{where}.pub").read_text().strip().split()
    if not case.security_key:
        return " ".join(source)
    fields = wire_fields(source[1])
    fields[0] = case.key_type.encode()
    fields.append(b"ssh:")
    return public_key_line(case.key_type, fields, source[2])


def wire_fields(blob: str) -> list[bytes]:
    """Return the complete SSH wire fields carried by a generated key."""
    raw = base64.b64decode(blob, validate=True)
    fields: list[bytes] = []
    offset = 0
    while offset < len(raw):
        size = int.from_bytes(raw[offset : offset + 4], "big")
        offset += 4
        fields.append(raw[offset : offset + size])
        offset += size
    return fields


def public_key_line(key_type: str, fields: list[bytes], comment: str) -> str:
    """Encode fields as an authorized_keys line."""
    raw = b"".join(len(field).to_bytes(4, "big") + field for field in fields)
    return f"{key_type} {base64.b64encode(raw).decode()} {comment}"


def test_key_cases_cover_key_types() -> None:
    assert {case.key_type for case in KEY_CASES} == sshkey.KEY_TYPES


@pytest.mark.parametrize("case", KEY_CASES)
def test_a_key_ssh_keygen_made_is_accepted(tmp_path: Path, case: KeyCase) -> None:
    """Every accepted type carries material generated by ssh-keygen."""
    line = generated(tmp_path, case)
    public = tmp_path / "candidate.pub"
    public.write_text(f"{line}\n")
    subprocess.run(["ssh-keygen", "-l", "-f", str(public)], check=True)
    assert sshkey.check(line) == line


@pytest.mark.parametrize("case", KEY_CASES)
def test_a_key_without_public_material_is_refused(
    tmp_path: Path, case: KeyCase
) -> None:
    line = generated(tmp_path, case)
    key_type, blob, comment = line.split()
    fields = wire_fields(blob)
    fields[case.public_material_field] = b""
    with pytest.raises(ConfigError, match="public material"):
        sshkey.check(public_key_line(key_type, fields, comment))


def test_a_comment_is_optional_and_extra_whitespace_is_normalised(tmp_path: Path) -> None:
    kind, blob, _ = generated(tmp_path, ED25519).split()
    assert sshkey.check(f"  {kind}   {blob}  ") == f"{kind} {blob}"


def test_a_body_declaring_another_type_is_refused(tmp_path: Path) -> None:
    """`ssh-rsa` in front of an ed25519 body is what a hand-edited file looks
    like, and sshd ignores the line rather than saying so."""
    _, blob, comment = generated(tmp_path, ED25519).split()
    with pytest.raises(ConfigError, match="declares a different type"):
        sshkey.check(f"ssh-rsa {blob} {comment}")


@pytest.mark.parametrize(
    "line",
    ["", "ssh-ed25519", "ssh-foo AAAA", "ssh-ed25519 not+base64!!", "-----BEGIN"],
)
def test_what_is_not_a_key_is_named_rather_than_written(line: str) -> None:
    with pytest.raises(ConfigError):
        sshkey.check(line)


def test_a_private_key_is_refused(tmp_path: Path) -> None:
    """Pointing at the wrong file of the pair is the common mistake, and the
    private half must never reach an authorized_keys file."""
    subprocess.run(
        ["ssh-keygen", "-q", "-t", "ed25519", "-N", "", "-f", str(tmp_path / "k")], check=True
    )
    private = (tmp_path / "k").read_text().splitlines()[0]
    with pytest.raises(ConfigError):
        sshkey.check(private)


def test_only_the_gentoozh_paste_gets_a_raw_path() -> None:
    """That host serves an HTML page at the address a browser shows; every
    other address is used as it was given."""
    assert raw_url("https://paste.gentoozh.org/vQTZ") == "https://paste.gentoozh.org/raw/vQTZ"
    assert raw_url("https://paste.gentoozh.org/raw/vQTZ") == "https://paste.gentoozh.org/raw/vQTZ"
    assert raw_url("https://example.com/id_ed25519.pub") == "https://example.com/id_ed25519.pub"
    assert raw_url("https://github.com/zakkaus.keys") == "https://github.com/zakkaus.keys"
    assert url_for("hjq+353Jzfk") == "https://paste.gentoozh.org/raw/hjq+353Jzfk"


def test_a_key_that_decodes_but_holds_one_field_is_refused() -> None:
    """A body with only its type and no key material: base64 is fine and the
    type matches, so nothing before the field count catches it."""
    body = base64.b64encode(
        len(b"ssh-ed25519").to_bytes(4, "big") + b"ssh-ed25519"
    ).decode()
    with pytest.raises(ConfigError, match="does not have the fields"):
        sshkey.check(f"ssh-ed25519 {body}")


def test_a_refused_key_is_not_quoted_back() -> None:
    """This is the field a password or a private key is pasted into by mistake,
    and every error here reaches the log, `install.jsonl` and the paste an
    operator sends to somebody else."""
    import pytest

    from gentoo_install.errors import ConfigError
    from gentoo_install.model import sshkey

    secret = "correct-horse-battery-staple"
    for line in (secret, f"{secret} body", f"ssh-ed25519 {secret}"):
        with pytest.raises(ConfigError) as raised:
            sshkey.check(line)
        assert secret not in str(raised.value), str(raised.value)

    # Negative control: a refusal still says which types are accepted, so the
    # rule above cannot be met by a message that carries nothing at all.
    with pytest.raises(ConfigError, match="ssh-ed25519"):
        sshkey.check("ssh-rsa2 AAAA")


def test_the_fingerprint_is_the_one_ssh_keygen_prints() -> None:
    """Both samples and both answers were read from `ssh-keygen -lf` on
    2026-08-24. Hashing the base64 text rather than the wire blob, or leaving
    the base64 padding on, produces a plausible string that no other tool
    agrees with."""
    from gentoo_install.model.sshkey import fingerprint

    ed25519 = (
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA9Q0PGF+/PUkbS6MTwK5Q5dqJE0"
        "+t0drU7HR0nzv7qb sample@example"
    )
    rsa = (
        "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDdlHUHRweaoLfv6h0VgfHTmQSXzxJMZZS7Ia4a3dP8"
        "I6ixYDosr01D5sRQQIZnmmXrrL9KXcHzCmmBnUwpLgZxW9ZyPLIcnImkXFt9nVbzlC/QPXp7bk1wT9ZN"
        "25I4PQAD1FyNmLBREHNUv10c+szitxacK/37S+WGachteiZ5PfWuR/ktDIIaaSeFfwE4XORC3Jh0vJYJ"
        "aBT1D7r78UaeAjX/jcHnuK31QeE8ntrtxQdtMVcLl5MVbKmYmaH2JwcXM2zDi2K/CFyayfDv3s+RDuHp"
        "kCZM1SU1sMduklNplaI5BpW6w1T4LMSKY/4EgWAYdFmvAG58P42qB8M3r9oV sample@example"
    )

    assert fingerprint(ed25519) == "SHA256:LblrAMoRSX1FbTHC09p0i3CyohVjuqZlCFA7p+iMV5A"
    assert fingerprint(rsa) == "SHA256:wlGCUednI5pRuDPDzpbdstjVq3awqyOcFoTpDAdIxbE"
    # The comment carries a username and a hostname; the fingerprint is the
    # same key with a different one.
    assert fingerprint(ed25519.replace("sample@example", "someone@elsewhere")) == fingerprint(
        ed25519
    )


def test_swapping_an_authorized_key_changes_the_dry_run() -> None:
    """The description was the number of keys, so replacing the key that
    decides who can log in moved not one character of it."""
    from gentoo_install.model.sshkey import fingerprint
    from gentoo_install.plan.system import WriteAuthorizedKeys

    first = (
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA9Q0PGF+/PUkbS6MTwK5Q5dqJE0"
        "+t0drU7HR0nzv7qb sample@example"
    )
    second = (
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH8w6sgdmfNXN4gVQnnQ"
        "/5WQiY0oUPrQYr0SPTfnw2ah other@example"
    )
    assert fingerprint(first) != fingerprint(second)

    accounts = (("root", "/root"),)
    said = [
        WriteAuthorizedKeys(keys=(one,), accounts=accounts).describe() for one in (first, second)
    ]
    assert said[0] != said[1], said


def test_a_paste_with_a_password_is_encrypted_and_read_back_with_it() -> None:
    """wastebin encrypts an entry that carries a password — its README says
    ChaCha20Poly1305 with an argon2 hashed password — so the host cannot read
    it either. `payload` never sent the field, so the feature was unreachable.

    Measured against `paste.gentoozh.org` on 2026-08-31: `GET /raw/:id` with
    `wastebin-password` answers the text, and without it, or with the wrong
    one, answers 200 and an HTML form. Nothing but the body says so.
    """
    import json

    from gentoo_install.model import paste

    export = paste.export_for("config")
    without = json.loads(paste.payload("body", export))
    assert "password" not in without

    with_one = json.loads(paste.payload("body", export, password="testtest"))
    assert with_one["password"] == "testtest"

    assert paste.PASSWORD_HEADER == "wastebin-password"
    assert paste.looks_like_the_password_form('<!DOCTYPE html>\n<html lang="en">')
    assert not paste.looks_like_the_password_form("[disk]\nwipe = true\n")


def test_a_configuration_url_that_needs_a_password_says_so_not_parses_html() -> None:
    """A wrong password answers 200 and the form, so a reader that checks only
    the status hands an HTML page to `tomllib` and reports a syntax error at
    line 1 of a configuration the operator never wrote."""
    import urllib.request
    from io import BytesIO

    import pytest

    from gentoo_install.errors import ConfigError
    from gentoo_install.exec import config as exec_config
    from gentoo_install.exec import fetch

    class Form:
        def __enter__(self) -> "Form":
            return self

        def __exit__(self, *unused: object) -> None:
            return None

        def read(self, size: int = -1) -> bytes:
            del size
            return b'<!DOCTYPE html>\n<html lang="en"><body>password</body></html>'

    def answered(
        request: urllib.request.Request, proxy: object = None, timeout: float = 0.0
    ) -> Form:
        del request, proxy, timeout
        return Form()

    original = fetch._urlopen
    fetch._urlopen = answered  # the one call this reader makes
    try:
        with pytest.raises(ConfigError, match="encrypted paste"):
            exec_config.load_source("https://paste.gentoozh.org/raw/abc")
    finally:
        fetch._urlopen = original
